spring:
  application:
    name: Springverse

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

huggingface:
  api:
    key: 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
